version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "8080:5432"    
    volumes:
      - data-volume:/data/db
    networks:
      - dockernet
    environment:
      POSTGRES_USER:  matt
      POSTGRES_PASSWORD_FILE:
        - ./db/secrets/password:/run/secrets/postgres-passwrd
      POSTGRES_DB: kinect-db
volumes:
  data-volume:
networks:
  dockernet:
    external: true