version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "8080:5432"    
    volumes:
      - data-volume:/data/db
    networks:
      - dockernet
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: ${DATA}
      POSTGRES_DB: ${DATABASE}
volumes:
  data-volume:
networks:
  dockernet:
    external: true